#The account plugin needs to be configured.  The following values may be used to customize the account

common:
    # Source address for user emails
    email_from: 'jbasdf@jbasdf.com'

    # Destination email for system errors
    admin_email: 'admin@jbasdf.com'

    # Sent in emails to users
    application_url: 'http://localhost:3000/'

    # Sent in emails to users
    application_name: 'Application Name'

    # Email charset
    mail_charset: 'utf-8'

    # controls whether or not email is used
    automatically_activate: false
    
production:

development:

  
  
