#Configure global settings for the application

common:

    # Sent in emails to users
    application_name: 'Teachers Without Borders'

    # Email charset
    mail_charset: 'utf-8'

    # controls whether or not email is used
    automatically_activate: false
    
    enable_plone_integration: true
    
    delete_confirm: "Are you sure you want to delete?\nThis can not be undone."
    
    search_limit: 25
    
    site_name: 'Teachers Without Borders'
     
    youtube_base_url: "http://gdata.youtube.com/feeds/api/videos/"
    
    flickr_key: '311e11626af5e7b9518a960a687a9b9a'
    
    flickr_secret: '643cbb44766793f1'
           
    flickr_cache: "#{RAILS_ROOT}/config/flickr.cache"
     
    courses_website: "courses.twbtools.com"
    
    groups_website: "groups.twbtools.com"
    
    integrate_plone: true
    
production:

    # Source address for user emails
    email_from: 'info@teacherswithoutborders.org'

    # Destination email for system errors
    admin_email: 'admin@teacherswithoutborders.com'

    # Sent in emails to users
    application_url: 'connect.twbtools.com'

    mailer_to_address: 'info@teacherswithoutborders.org'
    
    # for cookies that need to work across all subdomains (the plone site)
    application_base_url: '.connect.twbtools.com' 
    
    # configuration for plone xml rpc call that creates user folders
    plone_xmlrpc_port: 8088    
    plone_xmlrpc_path: '/plone'    
    plone_xmlrpc_server: "10.6.0.4"
    
    
development:

    # Source address for user emails
    email_from: 'info@teacherswithoutborders.com'

    # Destination email for system errors
    admin_email: 'admin@teacherswithoutborders.com'

    # Sent in emails to users
    application_url: 'localhost:3000'

    mailer_to_address: 'info@teacherswithoutborders.com'
    
    # for cookies that need to work across all subdomains (the plone site)
    application_base_url: 'localhost:3000'
    
    # configuration for plone xml rpc call that creates user folders
    plone_xmlrpc_port: 80
    plone_xmlrpc_path: '/RPC2'
    plone_xmlrpc_server: "groups.twbtools.com"
    
test:

    # Source address for user emails
    email_from: 'info@teacherswithoutborders.com'

    # Destination email for system errors
    admin_email: 'admin@teacherswithoutborders.com'

    # Sent in emails to users
    application_url: 'localhost:3000'
    
    mailer_to_address: 'info@teacherswithoutborders.com'
    

    
    
    
