class CreateCountries < ActiveRecord::Migration
    
    def self.up
        create_table "countries", :force => true do |t|
            t.string "name",         :limit => 128, :default => "", :null => false
            t.string "abbreviation", :limit => 3,   :default => "", :null => false
        end
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Andorra','AD');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('United Arab Emirates','AE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Afghanistan','AF');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Antigua & Barbuda','AG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Anguilla','AI');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Albania','AL');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Armenia','AM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Netherlands Antilles','AN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Angola','AO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Antarctica','AQ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Argentina','AR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('American Samoa','AS');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Austria','AT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Australia','AU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Aruba','AW');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Azerbaijan','AZ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Bosnia and Herzegovina','BA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Barbados','BB');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Bangladesh','BD');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Belgium','BE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Burkina Faso','BF');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Bulgaria','BG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Bahrain','BH');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Burundi','BI');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Benin','BJ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Bermuda','BM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Brunei Darussalam','BN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Bolivia','BO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Brazil','BR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Bahama','BS');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Bhutan','BT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Burma (no longer exists)','BU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Bouvet Island','BV');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Botswana','BW');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Belarus','BY');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Belize','BZ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Canada','CA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Cocos (Keeling) Islands','CC');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Central African Republic','CF');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Congo','CG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Switzerland','CH');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('C√¥te D\\'ivoire (Ivory Coast)','CI');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Cook Iislands','CK');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Chile','CL');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Cameroon','CM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('China','CN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Colombia','CO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Costa Rica','CR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Czechoslovakia (no longer exists)','CS');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Cuba','CU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Cape Verde','CV');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Christmas Island','CX');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Cyprus','CY');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Czech Republic','CZ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('German Democratic Republic (no longer exists)','DD');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Germany','DE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Djibouti','DJ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Denmark','DK');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Dominica','DM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Dominican Republic','DO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Algeria','DZ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Ecuador','EC');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Estonia','EE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Egypt','EG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Western Sahara','EH');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Eritrea','ER');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Spain','ES');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Ethiopia','ET');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Finland','FI');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Fiji','FJ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Falkland Islands (Malvinas)','FK');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Micronesia','FM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Faroe Islands','FO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('France','FR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('France, Metropolitan','FX');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Gabon','GA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('United Kingdom (Great Britain)','GB');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Grenada','GD');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Georgia','GE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('French Guiana','GF');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Ghana','GH');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Gibraltar','GI');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Greenland','GL');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Gambia','GM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Guinea','GN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Guadeloupe','GP');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Equatorial Guinea','GQ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Greece','GR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('South Georgia and the South Sandwich Islands','GS');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Guatemala','GT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Guam','GU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Guinea-Bissau','GW');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Guyana','GY');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Hong Kong','HK');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Heard & McDonald Islands','HM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Honduras','HN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Croatia','HR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Haiti','HT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Hungary','HU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Indonesia','ID');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Ireland','IE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Israel','IL');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('India','IN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('British Indian Ocean Territory','IO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Iraq','IQ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Islamic Republic of Iran','IR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Iceland','IS');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Italy','IT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Jamaica','JM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Jordan','JO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Japan','JP');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Kenya','KE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Kyrgyzstan','KG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Cambodia','KH');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Kiribati','KI');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Comoros','KM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('St. Kitts and Nevis','KN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Korea, Democratic People\\'s Republic of','KP');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Korea, Republic of','KR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Kuwait','KW');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Cayman Islands','KY');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Kazakhstan','KZ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Lao People\\'s Democratic Republic','LA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Lebanon','LB');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Saint Lucia','LC');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Liechtenstein','LI');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Sri Lanka','LK');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Liberia','LR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Lesotho','LS');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Lithuania','LT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Luxembourg','LU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Latvia','LV');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Libyan Arab Jamahiriya','LY');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Morocco','MA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Monaco','MC');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Moldova, Republic of','MD');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Madagascar','MG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Marshall Islands','MH');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Mali','ML');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Mongolia','MN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Myanmar','MM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Macau','MO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Northern Mariana Islands','MP');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Martinique','MQ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Mauritania','MR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Monserrat','MS');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Malta','MT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Mauritius','MU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Maldives','MV');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Malawi','MW');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Mexico','MX');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Malaysia','MY');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Mozambique','MZ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Namibia','NA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('New Caledonia','NC');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Niger','NE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Norfolk Island','NF');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Nigeria','NG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Nicaragua','NI');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Netherlands','NL');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Norway','NO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Nepal','NP');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Nauru','NR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Neutral Zone (no longer exists)','NT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Niue','NU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('New Zealand','NZ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Oman','OM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Panama','PA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Peru','PE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('French Polynesia','PF');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Papua New Guinea','PG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Philippines','PH');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Pakistan','PK');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Poland','PL');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('St. Pierre & Miquelon','PM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Pitcairn','PN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Puerto Rico','PR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Portugal','PT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Palau','PW');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Paraguay','PY');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Qatar','QA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('R√©union','RE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Romania','RO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Russian Federation','RU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Rwanda','RW');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Saudi Arabia','SA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Solomon Islands','SB');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Seychelles','SC');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Sudan','SD');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Sweden','SE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Singapore','SG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('St. Helena','SH');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Slovenia','SI');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Svalbard & Jan Mayen Islands','SJ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Slovakia','SK');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Sierra Leone','SL');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('San Marino','SM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Senegal','SN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Somalia','SO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Suriname','SR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Sao Tome & Principe','ST');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Union of Soviet Socialist Republics (no longer exists)','SU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('El Salvador','SV');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Syrian Arab Republic','SY');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Swaziland','SZ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Turks & Caicos Islands','TC');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Chad','TD');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('French Southern Territories','TF');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Togo','TG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Thailand','TH');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Tajikistan','TJ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Tokelau','TK');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Turkmenistan','TM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Tunisia','TN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Tonga','TO');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('East Timor','TP');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Turkey','TR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Trinidad & Tobago','TT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Tuvalu','TV');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Taiwan, Province of China','TW');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Tanzania, United Republic of','TZ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Ukraine','UA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Uganda','UG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('United States Minor Outlying Islands','UM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('United States of America','US');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Uruguay','UY');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Uzbekistan','UZ');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Vatican City State (Holy See)','VA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('St. Vincent & the Grenadines','VC');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Venezuela','VE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('British Virgin Islands','VG');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('United States Virgin Islands','VI');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Viet Nam','VN');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Vanuatu','VU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Wallis & Futuna Islands','WF');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Samoa','WS');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Democratic Yemen (no longer exists)','YD');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Yemen','YE');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Mayotte','YT');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Yugoslavia','YU');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('South Africa','ZA');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Zambia','ZM');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Zaire','ZR');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Zimbabwe','ZW');"
        execute "INSERT INTO countries (name, abbreviation) VALUES ('Unknown or unspecified country','ZZ');"
    end

    def self.down
        drop_table :countries
    end
    
end
