class TwbProfile < ActiveRecord::Migration
  def self.up
    add_column :users, :organization, :string
    add_column :users, :grade_experience, :integer
    add_column :users, :first_language, :integer
    add_column :users, :why_joined, :text
    add_column :users, :skills, :text
    add_column :users, :occupation, :text
    
    create_table "languages", :force => true do |t|
      t.string  "name"
      t.string  "english_name"
      t.integer "is_default", :default => 0
    end
    create_table "users_languages", :force => true do |t|
      t.integer  "user_id"
      t.integer  "language_id"
    end
    add_index :profiles_languages, [:profile_id, :language_id]
    add_index :profiles_languages, :profile_id
    execute "INSERT INTO languages (name,english_name,is_default) VALUES ('English','English',1);"
    execute "INSERT INTO languages (name,english_name) VALUES ('–º–∞–≥I–∞—Ä—É–ª –º–∞—ÜI','Afar');"
    execute "INSERT INTO languages (name,english_name) VALUES ('–±—ã–∑—à”ô–∞','Abkhazian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Afrikaans','Afrikaans');"
    execute "INSERT INTO languages (name,english_name) VALUES ('·ä†·àõ·à≠·äõ','Amharic');"
    execute "INSERT INTO languages (name,english_name) VALUES ('ÿßŸÑÿπÿ±ÿ®Ÿäÿ©','Arabic');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡¶Ö‡¶∏‡¶Æ‡¶ø‡ßü‡¶æ','Assamese');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Aymara','Aymara');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Az…ôri T√ºrk√ß…ôsi','Azerbaijani');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Bashkir','Bashkir');"
    execute "INSERT INTO languages (name,english_name) VALUES ('–ë–µ–ª–∞—Ä—É—Å–∫—ñ','Belarussian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('–ë—ä–ª–≥–∞—Ä—Å–∫–∏','Bulgarian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Bihari','Bihari');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Bislama','Bislama');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡¶¨‡¶æ‡¶Ç‡¶≤‡¶æ','Bengali');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡Ωñ‡Ωº‡Ωë‡ºã‡Ω¶‡æê‡Ωë‡ºã','Tibetan');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Bosanski','Bosnian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Brezhoneg','Breton');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Catal√†','Catalan');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Corsu','Corsican');"
    execute "INSERT INTO languages (name,english_name) VALUES ('ƒåe≈°tina','Czech');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Cymraeg','Welsh');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Dansk','Danish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Deutsch','German');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Bhutani','Indian Bhutani');"
    execute "INSERT INTO languages (name,english_name) VALUES ('ŒïŒªŒªŒ∑ŒΩŒπŒ∫Œ¨','Greek');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Esperanto','Esperanto');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Espa√±ol','Spanish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Eesti','Estonian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Euskara','Basque');"
    execute "INSERT INTO languages (name,english_name) VALUES ('ŸÅÿßÿ±ÿ≥€å','Persian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Suomi','Finnish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Fiji','Fiji');"
    execute "INSERT INTO languages (name,english_name) VALUES ('F√∏royska','Faroese');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Fran√ßais','French');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Frysk','Frisian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Gaeilge','Irish Gaelic');"
    execute "INSERT INTO languages (name,english_name) VALUES ('G√†idhlig','Scottish Gaelic');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Galego','Galician');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Guarani','Guarani');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡™ó‡´Å‡™ú‡™∞‡™æ‡™§‡´Ä','Gujarati');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Gaelg','Manx Gaelic');"
    execute "INSERT INTO languages (name,english_name) VALUES ('ŸáŸéŸàŸèÿ≥','Hausa');"
    execute "INSERT INTO languages (name,english_name) VALUES ('◊¢◊ë◊®◊ô◊™','Hebrew');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡§π‡§ø‡§Ç‡§¶‡•Ä','Hindi');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Hrvatski','Croatian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Magyar','Hungarian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('’Ä’°’µ’•÷Ä’ß’∂','Armenian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Interlingua','Interlingua');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Bahasa Indonesia','Indonesian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Interlingue','Interlingue');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Inupiak','Inupiak');"
    execute "INSERT INTO languages (name,english_name) VALUES ('√çslenska','Icelandic');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Italiano','Italian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('·êÉ·ìÑ·íÉ·ëé·ëê·ë¶','Inuktitut');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Êó•Êú¨Ë™û','Japanese');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Javanese','Javanese');"
    execute "INSERT INTO languages (name,english_name) VALUES ('·É•·Éê·É†·Éó·É£·Éö·Éò','Georgian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('ÔªóÔ∫éÔ∫ØÔ∫çÔªóÔ∫∏Ô∫é','Kazakh');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Greenlandic','Greenlandic');"
    execute "INSERT INTO languages (name,english_name) VALUES ('·ûÅ·üí·ûò·üÇ·ûö','Cambodian/Khmer');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡≤ï‡≤®‡≥ç‡≤®‡≤°','Kannada');"
    execute "INSERT INTO languages (name,english_name) VALUES ('ÌïúÍµ≠Ïñ¥','Korean');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡§ï‡§æ‡§Ω‡§∂‡•Å‡§∞','Kashmiri');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Kurd√≠','Kurdish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Kernewek','Cornish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('–ö—ã—Ä–≥—ã–∑','Kirghiz');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Latin','Latin');"
    execute "INSERT INTO languages (name,english_name) VALUES ('L√´tzebuergesch','Luxemburgish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Limburgs','Limburgish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Lingala','Lingala');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡∫û‡∫≤‡∫™‡∫≤‡∫•‡∫≤‡∫ß','Laotian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Lietuviskai','Lithuanian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Latvie≈°u','Latvian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Malagasy','Madagascarian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Maori','Maori');"
    execute "INSERT INTO languages (name,english_name) VALUES ('–ú–∞–∫–µ–¥–æ–Ω—Å–∫–∏','Macedonian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡¥Æ‡¥≤‡¥Ø‡¥æ‡¥≥‡¥Ç','Malayalam');"
    execute "INSERT INTO languages (name,english_name) VALUES ('–ú–æ–Ω–≥–æ–ª','Mongolian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Moldavian','Moldavian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡§Æ‡§∞‡§æ‡§†‡•Ä','Marathi');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Bahasa Melayu','Malay');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Malti','Maltese');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Burmese','Burmese');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Nauru','Nauruan');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡§®‡•á‡§™‡§æ‡§≤‡•Ä','Nepali');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Nederlands','Dutch');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Norsk','Norwegian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Nynorsk','Nynorsk');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Occitan','Occitan');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Oromo','Oromo');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡¨ì‡≠ú‡¨ø‡¨Ü','Oriya');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡®™‡©∞‡®ú‡®æ‡®¨‡©Ä','Punjabi');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Polski','Polish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Ÿæ⁄öÿ™Ÿà','Pashto');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Portugu√™s','Portuguese');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Quechua','Quechua');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Rhaeto-Romance','Rhaeto-Romance');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Kirundi','Kirundi');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Rom√¢nƒÉ','Romanian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('–†—É—Å—Å–∫–∏–π','Russian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Kiyarwanda','Kiyarwanda');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡§∏‡§Ç‡§∏‡•ç‡§ï‡•É‡§§','Sanskrit');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Sindhi','Sindhi');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Northern S√°mi','Northern S√°mi');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Sangho','Sangho');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Serbo-Croatian','Serbo-Croatian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Singhalese','Singhalese');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Slovenƒçina','Slovak');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Sloven≈°ƒçina','Slovenian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Samoan','Samoan');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Shona','Shona');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Somali','Somali');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Shqip','Albanian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('—Å—Ä–ø—Å–∫–∏','Serbian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Siswati','Siswati');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Sesotho','Sesotho');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Sudanese','Sudanese');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Svenska','Swedish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Swahili','Swahili');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡Æ§‡ÆÆ‡Æø‡Æ¥','Tamil');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡∞§‡±Ü‡∞≤‡±Å‡∞ó‡±Å','Telugu');"
    execute "INSERT INTO languages (name,english_name) VALUES ('–¢–æ“∑–∏–∫–∏','Tadjik');"
    execute "INSERT INTO languages (name,english_name) VALUES ('‡πÑ‡∏ó‡∏¢','Thai');"
    execute "INSERT INTO languages (name,english_name) VALUES ('·âµ·åç·à≠·äõ','Tigrinya');"
    execute "INSERT INTO languages (name,english_name) VALUES ('—Ç“Ø—Ä–∫m–µ–Ω—á–µ','Turkmen');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Tagalog','Tagalog');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Setswana','Setswana');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Tonga','Tonga');"
    execute "INSERT INTO languages (name,english_name) VALUES ('T√ºrk√ße','Turkish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Tsonga','Tsonga');"
    execute "INSERT INTO languages (name,english_name) VALUES ('—Ç–∞—Ç–∞—Ä—á–∞','Tatar');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Twi','Twi');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Uigur','Uigur');"
    execute "INSERT INTO languages (name,english_name) VALUES ('–£–∫—Ä–∞—ó–Ω—Å—å–∫–∞','Ukrainian');"
    execute "INSERT INTO languages (name,english_name) VALUES ('ÿßÿ±ÿØŸà','Urdu');"
    execute "INSERT INTO languages (name,english_name) VALUES ('–é–∑–±–µ–∫—á–∞','Uzbek');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Ti·∫øng Vi·ªát','Vietnamese');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Volap√ºk','Volap√ºk');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Walon','Walloon');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Wolof','Wolof');"
    execute "INSERT INTO languages (name,english_name) VALUES ('isiXhosa','Xhosa');"
    execute "INSERT INTO languages (name,english_name) VALUES ('◊≤÷¥◊ì◊ô◊©','Yiddish');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Yor√πb√°','Yorouba');"
    execute "INSERT INTO languages (name,english_name) VALUES ('Zhuang','Zhuang');"
    execute "INSERT INTO languages (name,english_name) VALUES ('zh-HK','Á∞°È´î‰∏≠Êñá,Chinese - Traditional');"
    execute "INSERT INTO languages (name,english_name) VALUES ('zh-CN','ÁÆÄ‰Ωì‰∏≠Êñá,Chinese - Simplified');"
    execute "INSERT INTO languages (name,english_name) VALUES ('isiZulu','Zulu');"
  end

  def self.down
    remove_column :users, :organization
    remove_column :users, :grade_experience
    remove_column :users, :first_lagnuage
    drop_table "languages"
    drop_table "profiles_languages"
    
  end
end
