# class for communicating with salesforce
class Contact < ActiveRecord::Base
    establish_connection :salesforce_production
    #include ActiveSalesforce::ActiveRecord::Mixin
    #set_table_name "contact"
end

# Salesforce Contact fields:
# last_name: "Guy", 
# first_name: "Test", 
# salutation: nil, 
# name: "Test Guy", 
# other_street: nil, 
# other_city: nil, 
# other_state: nil, 
# other_postal_code: nil, 
# other_country: nil, 
# mailing_street: nil, 
# mailing_city: nil, 
# mailing_state: nil, 
# mailing_postal_code: nil, 
# mailing_country: "US", 
# phone: nil, 
# fax: nil, 
# mobile_phone: nil, 
# home_phone: nil, 
# other_phone: nil, 
# reports_to_id: nil, 
# email: "testguy@example.com", 
# title: "The Main Tester (not a real user)", 
# department: nil, 
# lead_source: nil, 
# birthdate: nil, 
# description: nil, 
# owner_id: "003300000033d5jMMM", 
# has_opted_out_of_email: false, 
# do_not_call: false, 
# created_date: "2008-01-16 23:18:59", 
# created_by_id: "003300000033d5jMMM", 
# last_modified_date: "2008-07-03 00:05:46", 
# last_modified_by_id: "003300000033d5jMMM", 
# system_modstamp: "2008-07-03 00:05:46", 
# last_activity_date: "2008-01-16", 
# last_cu_request_date: nil, 
# last_cu_update_date: nil, 

# TWB specific
# contact_full_name__c: "<a href=\"/0044000000GGggG\" target=\"_blank\">Guy, Te...", 
# onen_household_id__c: "s0220000002BB3bBBB", 
# marital_status__c: nil, 
# household_links__c: "<a href=\"/servlet/servlet.Integration?lid=07M900000...", 
# volunteer_interests__c: nil, 
# deceased__c: false, 
# map__c: "<a href=\"/servlet/servlet.Integration?lid=00a900000...", 
# spouse_name__c: nil, 
# addressee__c: nil, 
# contact_name_dashboard__c: "Guy, Test", 
# philanthropic_interests__c: nil, 
# head_of_household__c: false, 
# certified__c: false, 
# age__c: nil, 
# do_not_mail__c: false, 
# member__c: false, 
# past_member__c: false, 
# partner__c: false, 
# twb_staff_member__c: true, 
# board_member__c: false, 
# volunteer__c: false, 
# country_coordinator__c: false, 
# paid__c: false, 
# if_so_rate_per_hour__c: nil, 
# wordpress_id__c: "1", 
# wordpress_login__c: "jbasdf", 
# employer__c: nil, 
# grade_level_experience__c: nil, 
# interest_areas__c: nil, 
# additional_skills__c: nil, 
# giraffe_heroes__c: false, 
# my_tec_c__c: false, 
# twb_tools__c: false, 
# twb_canada__c: false, 
# newsletter__c: false, 
# why_joined__c: nil, 
# occupation__c: nil, 
# first_language__c: nil, 
# other_languages__c: nil